server:
  port: 9000
kafka:
  topic: kafkaTopic
  consumerGroupId: group_id
  server: localhost:9092

spring:
  mail.host: smtp.gmail.com
  mail.port: 587
  mail.username: prafultest21@gmail.com
  mail.password: Prafultest@21
  mail.properties.mail.smtp.auth: true
  mail.properties.mail.smtp.starttls.enable: true